version: '2'

services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    networks:
      - code
    depends_on:
      - postgres
    volumes:
      - "./flask:/app"
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    networks:
      - code
    ports:
      - "80:80"

  postgres:
    restart: always
    container_name: postgres
    image: postgres:latest
    networks:
      - code
    environment:
      - POSTGRES_USER=david
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=david
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  code: